"""Export published product inventory from PostgreSQL to D1 SQL migration.

Usage (from backend directory):
    python -m scripts.export_postgres_to_d1 --output-sql ../cloudflare/worker/migrations/0003_seed_inventory.sql
"""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from sqlalchemy import or_, select

from app.database import async_session_factory
from app.models.product import Product, ProductFamily, ProductInventory
from app.models.vendor import Vendor


async def export_to_d1_sql(output_sql_path: Path) -> int:
    output_sql_path.parent.mkdir(parents=True, exist_ok=True)
    
    async with async_session_factory() as session:
        stmt = (
            select(Product, Vendor, ProductFamily)
            .join(Vendor, Vendor.id == Product.vendor_id)
            .outerjoin(ProductFamily, ProductFamily.id == Product.family_id)
            .where(
                Product.is_active.is_(True),
                Product.publication_status == "published",
                Vendor.is_active.is_(True),
                or_(Product.family_id.is_(None), ProductFamily.is_published.is_(True)),
            )
            .order_by(Product.sku, Product.id)
        )
        product_rows = (await session.execute(stmt)).all()

        # Query all inventory records
        inv_result = await session.execute(select(ProductInventory))
        inv_map = {str(inv.product_id): inv.available_quantity for inv in inv_result.scalars().all()}

        lines = [
            "-- Seed authoritative inventory exported from live PostgreSQL database",
            "-- Generated by backend.scripts.export_postgres_to_d1",
            "-- Stock quantities reflect authoritative live inventory (never invented)",
            "",
            "-- Product Inventory",
        ]

        count = 0
        for p, vendor, family in product_rows:
            if not p.id or not p.title:
                continue
            
            # Concept products must not be active for purchase
            is_concept = bool(family and family.is_concept) or (
                isinstance(p.specifications, dict) and p.specifications.get("concept") is True
            )
            is_active = 0 if is_concept else 1
            
            price_minor = int(round(float(p.base_price) * 100))
            
            # Exact authoritative stock from inventory record, never invented
            stock = inv_map.get(str(p.id))
            units = max(0, int(stock)) if stock is not None else 0
            
            title_escaped = p.title.replace("'", "''")
            pid_escaped = str(p.id).replace("'", "''")
            
            lines.append(
                f"INSERT INTO inventory (product_id, title, available_units, price_minor, currency, is_active) "
                f"VALUES ('{pid_escaped}', '{title_escaped}', {units}, {price_minor}, 'INR', {is_active}) "
                f"ON CONFLICT(product_id) DO UPDATE SET "
                f"title = excluded.title, price_minor = excluded.price_minor, available_units = excluded.available_units, is_active = excluded.is_active;"
            )
            count += 1

        output_sql_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Exported {count} verified products from PostgreSQL to D1 migration SQL: {output_sql_path}")
        return count


def main() -> None:
    parser = argparse.ArgumentParser(description="Export PostgreSQL inventory to D1 migration SQL.")
    parser.add_argument(
        "--output-sql",
        type=Path,
        default=Path("../cloudflare/worker/migrations/0003_seed_inventory.sql"),
        help="Path for generated D1 SQL seed migration",
    )
    args = parser.parse_args()
    asyncio.run(export_to_d1_sql(args.output_sql))


if __name__ == "__main__":
    main()
