"""Export active product inventory and customer fixtures from PostgreSQL to D1 SQL migration.

Usage (from backend directory):
    python -m scripts.export_postgres_to_d1 --output-sql ../cloudflare/worker/migrations/0003_seed_inventory.sql
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.database import async_session_factory
from app.models.product import Product, ProductInventory


async def export_to_d1_sql(output_sql_path: Path) -> int:
    output_sql_path.parent.mkdir(parents=True, exist_ok=True)
    
    async with async_session_factory() as session:
        result = await session.execute(
            select(Product).where(
                Product.is_active == True,  # noqa: E712
            )
        )
        products = result.scalars().all()

        # Query all inventory records
        inv_result = await session.execute(select(ProductInventory))
        inv_map = {str(inv.product_id): inv.available_quantity for inv in inv_result.scalars().all()}

        lines = [
            "-- Seed authoritative inventory exported from live PostgreSQL database",
            "-- Generated by backend.scripts.export_postgres_to_d1",
            "",
            "-- Standard test customer and address for staging & verification",
            "INSERT OR IGNORE INTO customers (id, phone, full_name, role) "
            "VALUES ('user-1', '+919999900000', 'Test Farmer', 'farmer');",
            "",
            "INSERT OR IGNORE INTO customer_addresses (id, customer_id, recipient_name, phone, address_line1, city, state, pincode, is_default) "
            "VALUES ('addr-1', 'user-1', 'Test Farmer', '+919999900000', 'Farm 12, Milk Road', 'Anand', 'Gujarat', '388001', 1);",
            "",
            "-- Product Inventory",
        ]

        count = 0
        for p in products:
            if not p.id or not p.title:
                continue
            price_minor = int(round(float(p.base_price) * 100))
            # Stock: check ProductInventory or default to 50
            stock = inv_map.get(str(p.id))
            units = stock if stock is not None and stock > 0 else 50
            title_escaped = p.title.replace("'", "''")
            pid_escaped = str(p.id).replace("'", "''")
            
            lines.append(
                f"INSERT INTO inventory (product_id, title, available_units, price_minor, currency, is_active) "
                f"VALUES ('{pid_escaped}', '{title_escaped}', {units}, {price_minor}, 'INR', 1) "
                f"ON CONFLICT(product_id) DO UPDATE SET "
                f"title = excluded.title, price_minor = excluded.price_minor, available_units = excluded.available_units;"
            )
            count += 1

        output_sql_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Exported {count} products from PostgreSQL to D1 migration SQL: {output_sql_path}")
        return count


def main() -> None:
    parser = argparse.ArgumentParser(description="Export PostgreSQL inventory to D1 migration SQL.")
    parser.add_argument(
        "--output-sql",
        type=Path,
        default=Path("../cloudflare/worker/migrations/0003_seed_inventory.sql"),
        help="Path for generated D1 SQL seed migration",
    )
    args = parser.parse_args()
    asyncio.run(export_to_d1_sql(args.output_sql))


if __name__ == "__main__":
    main()
